//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public bool presence { get; set; }
        public int idstudent { get; set; }
        public int idsubject { get; set; }

        public string DateShort { get => date.ToShortDateString(); }

        public string fioStudent { get => Student.fio; }

        public string titleSubject { get => Subject.title; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
