//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratory
    {
        public int id { get; set; }
        public string title { get; set; }
        public double maxball { get; set; }
        public Nullable<int> idSubject { get; set; }
        public string stitle { get=>Subject.title;}
        public int ids { get=>Subject.id;}

        public virtual Subject Subject { get; set; }
    }
}
